"""Adding departments table

Revision ID: 574350b8663f
Revises: 3e7a6f2a4a67
Create Date: 2025-09-16 21:40:16.349704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574350b8663f'
down_revision = '3e7a6f2a4a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
